- name: volume provisioning
  hosts: scaleio-sio-configuration
  tasks:
    - name: volume provisioning
      shell: |
        scli --login --username admin --password P@ssw0rd --approve_certificate

        scli --add_volume --protection_domain_name PD1 --storage_pool_name POOL1 --size_gb 8 --volume_name VOL001
        scli --add_volume --protection_domain_name PD1 --storage_pool_name POOL1 --size_gb 8 --volume_name VOL002
        scli --add_volume --protection_domain_name PD1 --storage_pool_name POOL1 --size_gb 16 --volume_name VOL003

        for i in `seq 1 3` ; do

        sleep 5
        scli --map_volume_to_sdc --sdc_ip 10.10.10.152 --protection_domain_name PD1 --storage_pool_name POOL1 --volume_name VOL001

        sleep 5
        dd if=/dev/zero of=/dev/scinia bs=1048576 count=4608
        scli --unmap_volume_from_sdc --volume_name VOL001 --sdc_ip 10.10.10.152 --i_am_sure 


        done
