- name: SIO CLUSTER CONFIG
  hosts: Primary-MDM
  tasks:
    - name:
      shell: |
        scli --create_mdm_cluster --master_mdm_ip "10.100.100.201,10.200.200.201" --master_mdm_management_ip 172.31.240.82 --master_mdm_name mdm1 --accept_license --use_nonsecure_communication
        sleep 4 
        scli --login --username admin --password admin --approve_certificate
        scli --set_password --old_password admin --new_password P@ssw0rd 
        scli --login --username admin --password P@ssw0rd --approve_certificate
        scli --add_standby_mdm --new_mdm_ip "10.100.100.202,10.200.200.202" --mdm_role manager --new_mdm_management_ip 172.31.240.83 --new_mdm_name mdm2
        sleep 3
        scli --add_standby_mdm --new_mdm_ip "10.100.100.203,10.200.200.203" --mdm_role tb --new_mdm_name tb 
        scli --switch_cluster_mode --cluster_mode 3_node --add_slave_mdm_name mdm2 --add_tb_name tb 
        
        sleep 2
         
        scli --add_protection_domain --protection_domain_name PD1
        scli --add_storage_pool --protection_domain_name PD1 --storage_pool_name POOL1
        sleep 2       
        scli --set_performance_parameters  --all_sds --all_sdc --apply_to_mdm --profile high_performance
        scli --rename_system --new_name SIOSYSTEM
        sleep 2

        scli --login --username admin --password P@ssw0rd --approve_certificate
        scli --add_sds --sds_ip "10.100.100.201,10.200.200.201" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds1 --i_am_sure
        sleep 20
        scli --add_sds --sds_ip "10.200.200.202,10.200.200.202" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds2 --i_am_sure
        sleep 20
        scli --add_sds --sds_ip "10.100.100.203,10.200.200.203" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds3 --i_am_sure
        sleep 20

        scli --add_sds --sds_ip "10.100.100.204,10.200.200.204" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds4 --i_am_sure
